// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	user_message.proto

It has these top-level messages:
	User
	GetUserByIdRequest
	RegisterUserRequest
	LoginUserRequest
	LoginResponse
	UserResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserByIdRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserByIdRequest) Reset()                    { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()               {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RegisterUserRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *RegisterUserRequest) Reset()                    { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()               {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginUserRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *LoginUserRequest) Reset()                    { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()               {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*GetUserByIdRequest)(nil), "GetUserByIdRequest")
	proto.RegisterType((*RegisterUserRequest)(nil), "RegisterUserRequest")
	proto.RegisterType((*LoginUserRequest)(nil), "LoginUserRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserResponse, error)
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/UserService/getUserById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/UserService/registerUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/UserService/loginUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	GetUserById(context.Context, *GetUserByIdRequest) (*UserResponse, error)
	RegisterUser(context.Context, *RegisterUserRequest) (*UserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserById(ctx, req.(*GetUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUserById",
			Handler:    _UserService_GetUserById_Handler,
		},
		{
			MethodName: "registerUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
		{
			MethodName: "loginUser",
			Handler:    _UserService_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_message.proto",
}

func init() { proto.RegisterFile("user_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x14, 0x84, 0x49, 0x4c, 0xc4, 0xbc, 0xb4, 0x45, 0xb7, 0x3d, 0xc4, 0x9c, 0x4a, 0x50, 0xa8, 0x07,
	0x17, 0x6d, 0xff, 0x41, 0x2f, 0x22, 0x78, 0x5a, 0xf1, 0xe2, 0x45, 0x52, 0xf3, 0x08, 0x8b, 0x4d,
	0x36, 0xee, 0xdb, 0x2a, 0xfe, 0x20, 0xff, 0xa7, 0xec, 0xc6, 0xa8, 0x8d, 0x0a, 0x3d, 0x4e, 0xe6,
	0xcb, 0x0c, 0xf3, 0x16, 0xd8, 0x86, 0x50, 0x3f, 0x54, 0x48, 0x94, 0x97, 0xc8, 0x1b, 0xad, 0x8c,
	0xca, 0x0a, 0x08, 0xee, 0x08, 0x35, 0x1b, 0x81, 0x2f, 0x8b, 0xc4, 0x9b, 0x7a, 0xb3, 0x50, 0xf8,
	0xb2, 0x60, 0x13, 0x08, 0xb1, 0xca, 0xe5, 0x3a, 0xf1, 0xa7, 0xde, 0x2c, 0x12, 0xad, 0x60, 0x29,
	0x1c, 0xd8, 0x8c, 0x3a, 0xaf, 0x30, 0xd9, 0x73, 0xc6, 0x97, 0xb6, 0x5e, 0x93, 0x13, 0xbd, 0x2a,
	0x5d, 0x24, 0x41, 0xeb, 0x75, 0x3a, 0x3b, 0x01, 0x76, 0x85, 0xc6, 0x16, 0x2d, 0xdf, 0xae, 0x0b,
	0x81, 0xcf, 0x1b, 0x24, 0xd3, 0xef, 0xcc, 0x2e, 0x60, 0x2c, 0xb0, 0x94, 0x64, 0x50, 0x5b, 0xb4,
	0xc3, 0x8e, 0x21, 0xb0, 0x25, 0x0e, 0x8c, 0xe7, 0x21, 0x77, 0x9e, 0xfb, 0x94, 0x9d, 0xc3, 0xe1,
	0x8d, 0x2a, 0x65, 0xbd, 0x23, 0x7e, 0x0a, 0x43, 0x87, 0x0b, 0xa4, 0x46, 0xd5, 0x84, 0x76, 0xa5,
	0x51, 0x4f, 0x58, 0x3b, 0x38, 0x12, 0xad, 0xc8, 0xce, 0x60, 0xd0, 0x06, 0x7e, 0x52, 0xff, 0x27,
	0xce, 0xdf, 0x3d, 0x88, 0xad, 0xbc, 0x45, 0xfd, 0x22, 0x1f, 0x91, 0x5d, 0x42, 0x5c, 0x7e, 0x0f,
	0x65, 0x63, 0xfe, 0x7b, 0x76, 0x3a, 0xe4, 0x5b, 0xe9, 0x0b, 0x18, 0xe8, 0x1f, 0xab, 0xd9, 0x84,
	0xff, 0x71, 0x84, 0xfe, 0x4f, 0x1c, 0xa2, 0x75, 0x37, 0x9c, 0x1d, 0xf1, 0xfe, 0x11, 0xd2, 0x11,
	0xdf, 0x1a, 0xba, 0x0c, 0xee, 0xfd, 0x66, 0xb5, 0xda, 0x77, 0x6f, 0xbe, 0xf8, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x26, 0x1f, 0xa8, 0x0d, 0x09, 0x02, 0x00, 0x00,
}
