FROM node:12.16.1-alpine

ENV HOME=/home/app

WORKDIR $HOME/supreme-api

COPY ["package.json", "yarn.lock", "$HOME/supreme-api/"]

RUN yarn install --frozen-lockfile --no-cache

COPY . $HOME/supreme-api

EXPOSE 3000
